// GamID PHASE 0b - SOCIAL PREVIEW VALIDATION LAB (TESTING ONLY, disposable).
//
// An isolated Worker that serves hand-written pages with explicit Open Graph / Twitter metadata in the FIRST HTTP response (no JavaScript), plus synthetic test media,
// so that what each social crawler really does can be observed. It is NOT the GamID public profile and shares nothing with it: no Supabase, no secrets, no real user data,
// no real Intro. Every request is logged as one JSON line (view with `wrangler tail`) so "the crawler fetched the page / the image / the video (with Range?)" can be
// told apart from "the preview rendered" and "the video played". Delete it with: wrangler delete --name gamid-social-lab
//
// Routes:  /  (index)   /x/<experiment>  (metadata pages)   /m/<file>  (media, allow-listed)   /robots.txt

const SITE = "GamID Social Lab (TESTING)";

// ---- media (allow-list; files live in ./assets, generated by generate-assets.ps1)
const MEDIA = {
  "card-1200x630.png": { type: "image/png" },
  "card-600x600.png": { type: "image/png" },
  "poster-1280x720.png": { type: "image/png" },
  "lab-h264-720p.mp4": { type: "video/mp4" },
  "lab-vp9-720p.webm": { type: "video/webm" },
  "lab-h264-big.mp4": { type: "video/mp4" },
  "lab-d3like-4k.webm": { type: "video/webm" },
};
// redirecting media URLs (redirect-behavior tests)
const MEDIA_REDIRECTS = { "redir-card.png": "card-1200x630.png", "redir-video.mp4": "lab-h264-720p.mp4" };

const OG = (key, value) => ["property", `og:${key}`, value];
const TW = (key, value) => ["name", `twitter:${key}`, value];

// ---- image / video tag builders
const imageTags = (o, file, w, h, alt) => [
  OG("image", `${o}/m/${file}`), OG("image:secure_url", `${o}/m/${file}`), OG("image:type", MEDIA[file]?.type || "image/png"),
  OG("image:width", String(w)), OG("image:height", String(h)), OG("image:alt", alt),
];
const videoTags = (o, file, w, h, type) => [
  OG("video", `${o}/m/${file}`), OG("video:url", `${o}/m/${file}`), OG("video:secure_url", `${o}/m/${file}`),
  OG("video:type", type || MEDIA[file].type), OG("video:width", String(w)), OG("video:height", String(h)),
];
const base = (o, id, title, description, type = "website") => [
  OG("site_name", SITE), OG("type", type), OG("title", title), OG("description", description), OG("url", `${o}/x/${id}`),
  ["name", "theme-color", "#62e7ff"],
];

// ---- the experiments. Each one is fully deterministic except c1 (a per-request token, on purpose).
// `meta(o)` returns the tags; `status`/`location` shape the HTTP response; `human` is what a person sees in a browser.
const EXPERIMENTS = {
  s1: {
    group: "static image", title: "S1 - standard static Open Graph card",
    what: "og:image 1200x630 PNG with explicit width/height/type/alt + twitter:card=summary_large_image. Baseline for every platform.",
    meta: o => [...base(o, "s1", "GamID Lab S1 - static image card", "Phase 0b lab. Standard Open Graph image 1200x630, direct HTTP 200."), ...imageTags(o, "card-1200x630.png", 1200, 630, "Lab card S1"),
      TW("card", "summary_large_image"), TW("title", "GamID Lab S1 - static image card"), TW("description", "Phase 0b lab. Standard Open Graph image."), TW("image", `${o}/m/card-1200x630.png`)],
    image: "card-1200x630.png",
  },
  s2: {
    group: "static image", title: "S2 - square image, twitter:card=summary",
    what: "600x600 PNG with twitter:card=summary (small card). Shows how each platform lays out a square thumbnail.",
    meta: o => [...base(o, "s2", "GamID Lab S2 - square image", "Phase 0b lab. Square 600x600 image, twitter:card=summary."), ...imageTags(o, "card-600x600.png", 600, 600, "Lab card S2"),
      TW("card", "summary"), TW("title", "GamID Lab S2 - square image"), TW("description", "Square image, summary card."), TW("image", `${o}/m/card-600x600.png`)],
    image: "card-600x600.png",
  },
  s3: {
    group: "redirect", title: "S3 - og:image URL that 302-redirects to the image",
    what: "The page is a normal 200, but og:image points to /m/redir-card.png, which answers 302 -> the real PNG. Does the crawler follow an image redirect?",
    meta: o => [...base(o, "s3", "GamID Lab S3 - image via redirect", "Phase 0b lab. og:image is a 302 redirect."),
      OG("image", `${o}/m/redir-card.png`), OG("image:secure_url", `${o}/m/redir-card.png`), OG("image:type", "image/png"), OG("image:width", "1200"), OG("image:height", "630"),
      TW("card", "summary_large_image"), TW("image", `${o}/m/redir-card.png`)],
    image: "card-1200x630.png",
  },
  r1: { group: "redirect", title: "R1 - page answers HTTP 302 to S1", what: "The URL itself redirects (302). Metadata exists only after the redirect. Does the crawler follow it?", redirect: { status: 302, to: "/x/s1" }, meta: () => [] },
  r2: { group: "redirect", title: "R2 - page answers HTTP 301 to S1", what: "Same, permanent (301).", redirect: { status: 301, to: "/x/s1" }, meta: () => [] },
  r3: {
    group: "redirect", title: "R3 - HTTP 200 with tags + meta-refresh/JS redirect in the body",
    what: "Tags are in the 200 body; the body ALSO redirects humans (meta refresh). Crawlers do not run scripts, so this shows tags win over client-side redirects (the GamID 404.html pattern, but with tags).",
    meta: o => [...base(o, "r3", "GamID Lab R3 - 200 + client redirect", "Phase 0b lab. Tags in the 200 body; the page redirects humans by meta refresh."), ...imageTags(o, "card-1200x630.png", 1200, 630, "Lab card R3"), TW("card", "summary_large_image")],
    head: () => `<meta http-equiv="refresh" content="6;url=/x/s1">`, image: "card-1200x630.png",
  },
  n1: {
    group: "status", title: "N1 - HTTP 404 status WITH full tags",
    what: "Complete Open Graph tags, but the HTTP status is 404 (what GitHub Pages returns for /@handle). Does the crawler ignore a non-200 page?",
    status: 404,
    meta: o => [...base(o, "n1", "GamID Lab N1 - 404 with tags", "Phase 0b lab. Full tags on an HTTP 404 response."), ...imageTags(o, "card-1200x630.png", 1200, 630, "Lab card N1"), TW("card", "summary_large_image")],
    image: "card-1200x630.png",
  },
  n2: {
    group: "status", title: "N2 - HTTP 200 with <meta name=robots content=noindex>",
    what: "Full tags plus noindex (the current GamID public shell carries noindex). Does noindex change any link preview?",
    meta: o => [...base(o, "n2", "GamID Lab N2 - noindex", "Phase 0b lab. Full tags plus a robots noindex meta."), ...imageTags(o, "card-1200x630.png", 1200, 630, "Lab card N2"), TW("card", "summary_large_image"), ["name", "robots", "noindex"]],
    image: "card-1200x630.png",
  },
  v1: {
    group: "video", title: "V1 - MP4 (H.264/AAC 720p) + og:video, og:type=video.other, twitter:card=summary_large_image",
    what: "The most standard video markup: og:video / :url / :secure_url / :type / :width / :height, poster in og:image. The poster says POSTER ONLY; the video shows a running clock.",
    meta: o => [...base(o, "v1", "GamID Lab V1 - MP4 video", "Phase 0b lab. og:video MP4 (H.264/AAC 1280x720, 6 s).", "video.other"), ...videoTags(o, "lab-h264-720p.mp4", 1280, 720), ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V1"),
      TW("card", "summary_large_image"), TW("image", `${o}/m/poster-1280x720.png`)],
    video: "lab-h264-720p.mp4", image: "poster-1280x720.png",
  },
  v2: {
    group: "video", title: "V2 - same as V1 with twitter:card=player (no player URL)",
    what: "The variant Discord's draft docs mention (twitter:card=player). No twitter:player iframe, so X should ignore it; tests Discord / Telegram / others.",
    meta: o => [...base(o, "v2", "GamID Lab V2 - MP4 + twitter player card", "Phase 0b lab. og:video MP4 + twitter:card=player.", "video.other"), ...videoTags(o, "lab-h264-720p.mp4", 1280, 720), ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V2"),
      TW("card", "player"), TW("title", "GamID Lab V2"), TW("image", `${o}/m/poster-1280x720.png`)],
    video: "lab-h264-720p.mp4", image: "poster-1280x720.png",
  },
  v3: {
    group: "video", title: "V3 - WebM (VP9/Opus 720p) + og:video, video.other",
    what: "Same content as V1 but WebM/VP9. Which platforms accept WebM?",
    meta: o => [...base(o, "v3", "GamID Lab V3 - WebM video", "Phase 0b lab. og:video WebM (VP9/Opus 1280x720, 6 s).", "video.other"), ...videoTags(o, "lab-vp9-720p.webm", 1280, 720), ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V3"),
      TW("card", "summary_large_image"), TW("image", `${o}/m/poster-1280x720.png`)],
    video: "lab-vp9-720p.webm", image: "poster-1280x720.png",
  },
  v4: {
    group: "video", title: "V4 - CONTROL: MP4 og:video tags but og:type=website",
    what: "Identical video tags to V1 but og:type stays 'website'. If Discord requires video.other / player, this should show only the poster.",
    meta: o => [...base(o, "v4", "GamID Lab V4 - video tags, type website", "Phase 0b lab. og:video present, og:type=website."), ...videoTags(o, "lab-h264-720p.mp4", 1280, 720), ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V4"),
      TW("card", "summary_large_image"), TW("image", `${o}/m/poster-1280x720.png`)],
    video: "lab-h264-720p.mp4", image: "poster-1280x720.png",
  },
  v5: {
    group: "video", title: "V5 - larger MP4 (~9.2 MiB, H.264/AAC 720p, 12 s)",
    what: "Size probe: above the ~8 MB figure quoted for Discord's own embeds. Does the platform still play/embed it?",
    meta: o => [...base(o, "v5", "GamID Lab V5 - 9 MB MP4", "Phase 0b lab. og:video MP4 of about 9.2 MiB.", "video.other"), ...videoTags(o, "lab-h264-big.mp4", 1280, 720), ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V5"),
      TW("card", "summary_large_image"), TW("image", `${o}/m/poster-1280x720.png`)],
    video: "lab-h264-big.mp4", image: "poster-1280x720.png",
  },
  v6: {
    group: "video", title: "V6 - og:video URL that 302-redirects to the MP4",
    what: "The video URL answers 302 -> the real MP4. Does the crawler/player follow a media redirect?",
    meta: o => [...base(o, "v6", "GamID Lab V6 - video via redirect", "Phase 0b lab. og:video is a 302 redirect.", "video.other"),
      OG("video", `${o}/m/redir-video.mp4`), OG("video:url", `${o}/m/redir-video.mp4`), OG("video:secure_url", `${o}/m/redir-video.mp4`), OG("video:type", "video/mp4"), OG("video:width", "1280"), OG("video:height", "720"),
      ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V6"), TW("card", "summary_large_image")],
    video: "lab-h264-720p.mp4", image: "poster-1280x720.png",
  },
  v7: {
    group: "video", title: "V7 - D3-shaped clip: 3840x2160 WebM VP9/Opus, ~14 MiB, 11 s",
    what: "A SYNTHETIC clip with the same shape as the accepted Intro derivative (4K VP9 WebM ~14 MiB). Answers: could the current D3 format itself ever play in a card? (It is a made-up test pattern, not the real Intro.)",
    meta: o => [...base(o, "v7", "GamID Lab V7 - 4K WebM (D3-shaped)", "Phase 0b lab. og:video 3840x2160 VP9 WebM, about 14 MiB.", "video.other"), ...videoTags(o, "lab-d3like-4k.webm", 3840, 2160), ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V7"),
      TW("card", "summary_large_image"), TW("image", `${o}/m/poster-1280x720.png`)],
    video: "lab-d3like-4k.webm", image: "poster-1280x720.png",
  },
  v8: {
    group: "video", title: "V8 - X/Twitter player-card markup (twitter:player iframe + stream)",
    what: "twitter:card=player with an HTTPS iframe page (/x/frame) and a stream URL. X needs domain approval, so expect a plain link/summary; also shows whether Telegram breaks on twitter:player (reported).",
    meta: o => [...base(o, "v8", "GamID Lab V8 - X player card", "Phase 0b lab. twitter:card=player with iframe + stream.", "video.other"), ...videoTags(o, "lab-h264-720p.mp4", 1280, 720), ...imageTags(o, "poster-1280x720.png", 1280, 720, "Poster V8"),
      TW("card", "player"), TW("title", "GamID Lab V8"), TW("description", "player card"), TW("image", `${o}/m/poster-1280x720.png`),
      TW("player", `${o}/x/frame`), TW("player:width", "1280"), TW("player:height", "720"), TW("player:stream", `${o}/m/lab-h264-720p.mp4`), TW("player:stream:content_type", "video/mp4")],
    video: "lab-h264-720p.mp4", image: "poster-1280x720.png",
  },
  c1: {
    group: "cache", title: "C1 - refetch probe: a fresh random token in title/description on EVERY fetch",
    what: "Cache-Control: no-store. The preview shows the token of the fetch that produced it. Post it, note the token; re-post / post ?v=2 later. Same token = the platform cached; new token = it refetched. The Worker log lists every fetch.",
    dynamic: true,
    meta: (o, ctx) => [...base(o, "c1", `GamID Lab C1 - token ${ctx.token}`, `Fetch token ${ctx.token} at ${ctx.iso}`), ...imageTags(o, "card-1200x630.png", 1200, 630, "Lab card C1"), TW("card", "summary_large_image")],
    image: "card-1200x630.png",
  },
};

// ---- helpers
const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
const metaTag = ([attr, key, value]) => `<meta ${attr}="${esc(key)}" content="${esc(value)}">`;
const origin = request => new URL(request.url).origin;   // never hard-coded: the same code works on any hostname

function log(request, extra) {
  const url = new URL(request.url);
  const cf = request.cf || {};
  console.log(JSON.stringify({
    lab: 1, t: new Date().toISOString(), method: request.method, path: url.pathname, q: url.search || undefined,
    ua: request.headers.get("user-agent") || "-", range: request.headers.get("range") || undefined, accept: (request.headers.get("accept") || "").slice(0, 60) || undefined,
    human: request.headers.has("sec-fetch-mode") || undefined, country: cf.country, asOrg: cf.asOrganization, colo: cf.colo, ...extra,
  }));
}

function page(o, id, exp, ctx) {
  const tags = exp.meta(o, ctx);
  const media = [
    exp.image ? `<p><img src="${o}/m/${exp.image}" alt="" style="max-width:100%;height:auto;border:1px solid #444"></p>` : "",
    exp.video ? `<p><video controls preload="metadata" style="max-width:100%" poster="${o}/m/poster-1280x720.png"><source src="${o}/m/${exp.video}"></video></p>` : "",
  ].join("");
  const shown = tags.map(([a, k, v]) => `${a}=${k}  ->  ${v}`).join("\n");
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(exp.title)}</title>
${tags.map(metaTag).join("\n")}
${exp.head ? exp.head(o) : ""}</head>
<body style="font-family:system-ui,sans-serif;background:#0b0912;color:#eee;max-width:52rem;margin:2rem auto;padding:0 1rem">
<p><a style="color:#62e7ff" href="/">&larr; lab index</a> &middot; TESTING &middot; Phase 0b social preview validation lab (not the GamID profile)</p>
<h1 style="font-size:1.3rem">${esc(exp.title)}</h1><p>${esc(exp.what)}</p>${ctx.token ? `<p><b>Fetch token: ${esc(ctx.token)}</b> (${esc(ctx.iso)})</p>` : ""}
${media}<h2 style="font-size:1rem">Metadata served in the first HTTP response (HTTP ${exp.status || 200})</h2><pre style="white-space:pre-wrap;word-break:break-all;background:#15121f;padding:1rem">${esc(shown)}</pre>
</body></html>`;
  return html;
}

function indexPage(o) {
  const rows = Object.entries(EXPERIMENTS).map(([id, e]) => `<tr><td><a style="color:#62e7ff" href="/x/${id}">${o}/x/${id}</a></td><td>${esc(e.group)}</td><td>${esc(e.title)}</td></tr>`).join("\n");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${SITE}</title>
${[...base(o, "", `${SITE}`, "Phase 0b social preview validation lab index."), OG("url", `${o}/`), ...imageTags(o, "card-1200x630.png", 1200, 630, "Lab index"), TW("card", "summary_large_image")].map(metaTag).join("\n")}</head>
<body style="font-family:system-ui,sans-serif;background:#0b0912;color:#eee;max-width:60rem;margin:2rem auto;padding:0 1rem"><h1>${SITE}</h1>
<p>Isolated Phase 0b lab. No Supabase, no real profile data, no real Intro. Each URL below returns HTTP 200 (unless it is a status/redirect test) with explicit metadata in the first response.</p>
<table cellpadding="6" border="1" style="border-collapse:collapse;border-color:#333"><tr><th>URL</th><th>group</th><th>test</th></tr>${rows}</table></body></html>`;
}

function frameHtml(o) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>player frame</title></head><body style="margin:0;background:#000"><video controls autoplay muted playsinline style="width:100%;height:100vh" src="${o}/m/lab-h264-720p.mp4"></video></body></html>`;
}

// Cloudflare Workers Static Assets does NOT honor Range (observed: 200 + no Accept-Ranges), but video clients rely on 206. So this Worker implements single-range
// requests itself (see serveMedia).
function parseRange(header, size) {
  if (!header) return null;
  const m = /^bytes=(\d*)-(\d*)$/.exec(header.trim());
  if (!m || (m[1] === "" && m[2] === "")) return "invalid";
  let start, end;
  if (m[1] === "") { const n = Number(m[2]); if (n === 0) return "invalid"; start = Math.max(size - n, 0); end = size - 1; }
  else { start = Number(m[1]); end = m[2] === "" ? size - 1 : Math.min(Number(m[2]), size - 1); }
  return start > end || start >= size ? "invalid" : { start, end };
}
async function serveMedia(request, env, file) {
  const spec = MEDIA[file];
  if (!spec) return null;
  const o = origin(request);
  // Workers Static Assets responses carry NO Content-Length (GET or HEAD), and ignore Range. Media clients want both, so the lab buffers each file (all <= 15 MiB)
  // and answers with an exact Content-Length and correct 206 / 416 handling. (For production media this would be revisited: see the Phase 0b report.)
  const asset = await env.ASSETS.fetch(new Request(`${o}/${file}`, { method: "GET" }));   // uncompressed: no Accept-Encoding is forwarded
  if (!asset.ok) return asset;
  const buf = await asset.arrayBuffer();
  const size = buf.byteLength;
  const out = new Headers({ "Content-Type": spec.type, "Accept-Ranges": "bytes", "Cache-Control": "public, max-age=300", "Access-Control-Allow-Origin": "*" });
  const range = parseRange(request.headers.get("range"), size);
  if (range === "invalid") { out.set("Content-Range", `bytes */${size}`); return new Response(null, { status: 416, headers: out }); }
  if (range) {
    out.set("Content-Range", `bytes ${range.start}-${range.end}/${size}`);
    out.set("Content-Length", String(range.end - range.start + 1));
    return new Response(request.method === "HEAD" ? null : buf.slice(range.start, range.end + 1), { status: 206, headers: out });
  }
  out.set("Content-Length", String(size));
  return new Response(request.method === "HEAD" ? null : buf, { status: 200, headers: out });
}
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const o = origin(request);
    const path = url.pathname;
    if (request.method !== "GET" && request.method !== "HEAD") { log(request, { status: 405 }); return new Response("Method not allowed", { status: 405 }); }

    if (path === "/robots.txt") { log(request, { status: 200, kind: "robots" }); return new Response("User-agent: Googlebot\nDisallow: /\nUser-agent: Bingbot\nDisallow: /\n", { headers: { "Content-Type": "text/plain" } }); }

    if (path === "/" || path === "") {
      log(request, { status: 200, kind: "index" });
      return new Response(indexPage(o), { headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" } });
    }

    if (path === "/x/frame") { log(request, { status: 200, kind: "frame" }); return new Response(frameHtml(o), { headers: { "Content-Type": "text/html; charset=utf-8" } }); }

    const exp = path.startsWith("/x/") ? EXPERIMENTS[path.slice(3)] : null;
    if (exp) {
      const id = path.slice(3);
      if (exp.redirect) {
        log(request, { status: exp.redirect.status, kind: "page-redirect", exp: id });
        return new Response(null, { status: exp.redirect.status, headers: { Location: `${o}${exp.redirect.to}`, "Cache-Control": "no-store" } });
      }
      const ctx = exp.dynamic ? { token: crypto.randomUUID().slice(0, 8), iso: new Date().toISOString() } : {};
      const status = exp.status || 200;
      log(request, { status, kind: "page", exp: id, token: ctx.token });
      return new Response(request.method === "HEAD" ? null : page(o, id, exp, ctx), {
        status, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": exp.dynamic ? "no-store" : "public, max-age=60" },
      });
    }

    if (path.startsWith("/m/")) {
      const file = decodeURIComponent(path.slice(3));
      if (MEDIA_REDIRECTS[file]) {
        log(request, { status: 302, kind: "media-redirect", file });
        return new Response(null, { status: 302, headers: { Location: `${o}/m/${MEDIA_REDIRECTS[file]}`, "Cache-Control": "no-store" } });
      }
      const res = await serveMedia(request, env, file);
      if (res) { log(request, { status: res.status, kind: "media", file, bytes: res.headers.get("content-length") || undefined }); return res; }
    }

    log(request, { status: 404, kind: "notfound" });
    return new Response("Not found", { status: 404, headers: { "Content-Type": "text/plain" } });
  },
};
