steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -f, worker/Dockerfile, -t, 'asia-southeast1-docker.pkg.dev/gamid-testing/gamid-workers/intro-processing:usage-${_CHECKPOINT}', .]
images:
  - 'asia-southeast1-docker.pkg.dev/gamid-testing/gamid-workers/intro-processing:usage-${_CHECKPOINT}'
options:
  logging: CLOUD_LOGGING_ONLY
